//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfChatClient.ChatServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChatServiceReference.IChatContract", CallbackContract=typeof(WpfChatClient.ChatServiceReference.IChatContractCallback))]
    internal interface IChatContract {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatContract/SendToMainChat")]
        void SendToMainChat(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatContract/SendToMainChat")]
        System.Threading.Tasks.Task SendToMainChatAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatContract/SendToPersonalChat")]
        void SendToPersonalChat(string reciever, string message, bool sendToSender);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatContract/SendToPersonalChat")]
        System.Threading.Tasks.Task SendToPersonalChatAsync(string reciever, string message, bool sendToSender);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatContract/IamIn")]
        void IamIn(string name);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatContract/IamIn")]
        System.Threading.Tasks.Task IamInAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IChatContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatContract/RefreshMainChat")]
        void RefreshMainChat(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatContract/RefreshPersonalChat")]
        void RefreshPersonalChat(string name, string message, bool finished);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatContract/RefreshClientList")]
        void RefreshClientList(string name, bool quitted);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatContract/FullRefreshClientList")]
        void FullRefreshClientList(string[] names);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IChatContractChannel : WpfChatClient.ChatServiceReference.IChatContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ChatContractClient : System.ServiceModel.DuplexClientBase<WpfChatClient.ChatServiceReference.IChatContract>, WpfChatClient.ChatServiceReference.IChatContract {
        
        public ChatContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendToMainChat(string message) {
            base.Channel.SendToMainChat(message);
        }
        
        public System.Threading.Tasks.Task SendToMainChatAsync(string message) {
            return base.Channel.SendToMainChatAsync(message);
        }
        
        public void SendToPersonalChat(string reciever, string message, bool sendToSender) {
            base.Channel.SendToPersonalChat(reciever, message, sendToSender);
        }
        
        public System.Threading.Tasks.Task SendToPersonalChatAsync(string reciever, string message, bool sendToSender) {
            return base.Channel.SendToPersonalChatAsync(reciever, message, sendToSender);
        }
        
        public void IamIn(string name) {
            base.Channel.IamIn(name);
        }
        
        public System.Threading.Tasks.Task IamInAsync(string name) {
            return base.Channel.IamInAsync(name);
        }
    }
}
