//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDiskInfoProxyClient.MyDiskInfoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyDiskInfoServiceReference.IMyDiskInfoServer")]
    public interface IMyDiskInfoServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyDiskInfoServer/GetFreeSpace", ReplyAction="http://tempuri.org/IMyDiskInfoServer/GetFreeSpaceResponse")]
        string GetFreeSpace(string diskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyDiskInfoServer/GetFreeSpace", ReplyAction="http://tempuri.org/IMyDiskInfoServer/GetFreeSpaceResponse")]
        System.Threading.Tasks.Task<string> GetFreeSpaceAsync(string diskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyDiskInfoServer/GetTotalSpace", ReplyAction="http://tempuri.org/IMyDiskInfoServer/GetTotalSpaceResponse")]
        string GetTotalSpace(string diskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyDiskInfoServer/GetTotalSpace", ReplyAction="http://tempuri.org/IMyDiskInfoServer/GetTotalSpaceResponse")]
        System.Threading.Tasks.Task<string> GetTotalSpaceAsync(string diskName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyDiskInfoServerChannel : MyDiskInfoProxyClient.MyDiskInfoServiceReference.IMyDiskInfoServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyDiskInfoServerClient : System.ServiceModel.ClientBase<MyDiskInfoProxyClient.MyDiskInfoServiceReference.IMyDiskInfoServer>, MyDiskInfoProxyClient.MyDiskInfoServiceReference.IMyDiskInfoServer {
        
        public MyDiskInfoServerClient() {
        }
        
        public MyDiskInfoServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyDiskInfoServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyDiskInfoServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyDiskInfoServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetFreeSpace(string diskName) {
            return base.Channel.GetFreeSpace(diskName);
        }
        
        public System.Threading.Tasks.Task<string> GetFreeSpaceAsync(string diskName) {
            return base.Channel.GetFreeSpaceAsync(diskName);
        }
        
        public string GetTotalSpace(string diskName) {
            return base.Channel.GetTotalSpace(diskName);
        }
        
        public System.Threading.Tasks.Task<string> GetTotalSpaceAsync(string diskName) {
            return base.Channel.GetTotalSpaceAsync(diskName);
        }
    }
}
